-- ─────────────────────────────────────────────────────────────────────────────
-- 008_invoice_source.sql
--
-- Distinguishes regular point-of-sale invoices from invoices auto-generated by
-- the tailoring module (created for accounting/GST purposes at ready_for_pickup,
-- see lib/tailoring-invoice.ts). The Billing > Invoices list filters these out
-- by default (app/(auth)/billing/invoices/page.tsx) — they still exist for
-- accounting and remain viewable from the tailoring order's own detail page.
--
-- Additive/idempotent — safe to run against a populated database. Backfills
-- 'tailoring' for any invoice already linked as a tailoring order's real
-- invoice, or as a supplementary invoice of one.
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE invoices ADD COLUMN IF NOT EXISTS source VARCHAR(20) NOT NULL DEFAULT 'pos';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'invoices_source_check'
  ) THEN
    ALTER TABLE invoices ADD CONSTRAINT invoices_source_check
      CHECK (source IN ('pos', 'tailoring'));
  END IF;
END $$;

UPDATE invoices SET source = 'tailoring'
WHERE id IN (SELECT invoice_id FROM tailoring_orders WHERE invoice_id IS NOT NULL)
  AND source <> 'tailoring';

UPDATE invoices SET source = 'tailoring'
WHERE supplementary_of_invoice_id IN (SELECT invoice_id FROM tailoring_orders WHERE invoice_id IS NOT NULL)
  AND source <> 'tailoring';

CREATE INDEX IF NOT EXISTS idx_invoices_source ON invoices(source);
